name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Setup node.js
      uses: actions/setup-node@v1
      with:
        node-version: 14.4
    - name: Setup clang
      run: |
        sudo add-apt-repository 'deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-10 main'
        sudo apt update
        sudo apt install clang-10 clang-tidy-10
        
    - name: Setup graphical drivers
      run: |
        sudo apt install mesa-common-dev libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev
    - name: Print versions
      run: |
        echo "Node:"
        node -v
        echo ""
        echo "npm:"
        npm -v
        echo ""
        echo "clang:"
        clang-10 --version
        echo ""
        echo "clang-tidy:"
        clang-tidy-10 --version
        echo ""
        echo "make:"
        make -v
        echo ""
    - uses: actions/checkout@v2
    - name: Setup .env
      run: |
        touch $GITHUB_WORKSPACE/.env
        echo "CLANG_BIN=clang-10" >> $GITHUB_WORKSPACE/.env
        echo "CLANG_TIDY_BIN=clang-tidy-10" >> $GITHUB_WORKSPACE/.env
    - name: Setup
      run: make setup
    - name: Build
      run: make
